### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by ghost** [AmyrAhmady/openmp-models#1]
Would help for when you're just browsing for models

**Comment by AmyrAhmady** [comment]
This is just a base UI for my 3d model viewer, center part will have the 3D model renderer and some other elements on the right side

**Comment by ghost** [comment]
Ah okay, thought it may be related to that - should end up great

**Comment by AmyrAhmady** [comment]
@folkfork 
is there any chance you open your discord again?

**Comment by ghost** [comment]
Not for the time being, but maybe later once stuff starts clearing up. I'll send you a message when I do, but meanwhile still active on here :)

**Comment by dakyskye** [comment]
The later you open, the more you'll have to hear haha
